- name: install MariaDB
  apt:
    name: "{{ item }}"
    state: present
  loop:
  - mariadb-server
  - mariadb-client
  - python3-mysqldb

- name: allow access remotely mariadb-client
  lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^bind-address'
    line: bind-address = 0.0.0.0
  notify: 
  - restart mariadb

- name: add user in mariadb
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_pass }}"
    host: '%'
    priv: '*.*:ALL'
    state: present

- name: create database
  mysql_db:
    name: "{{ db_name }}"
    state: present